POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
  "title": "My second blog post",
  "author": "Matti Rantila",
  "url": "https://rantila.fi/",
  "likes": 0
}