POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NzVkNDNjYjgzYWViYjFkOGM4MTUxNSIsImlhdCI6MTY4NTU1MDI0MiwiZXhwIjoxNjg1NTUzODQyfQ.2cIOSHrd6gGQowxWIWivOHJ8CFie72mrlckf-5lJbKE

{
  "content": "mongolian bbq is a beast",
  "important": true
}